resourcestring                                     {english}

  rsProgName='SessionPropertyTool';
  capWaisen='&Orphaned items';
  hntWaisen='Find orphaned items in Session Properties.';
  capXMLcheck='&Check XML';
  hntXMLcheck='Find unused items in XML settings.';
  capClose='&Close';
  hntClose='Close programm (without saving)';
  capFilter='Only orphaned items';
  hntFilter='List only orphaned items.';
  capDelete='Delete unused items';
  hntDelete='Delete unused items in XML file.';
  capFunc='&Functions';
  hntStatus='Counter and status messages';
  hntStatusW='# Lines read / # Items / # Orphaned / Status messages';
  hntStatusO='# Lines read / # Objects / n/a / Status messages';

  ttOpenDialogLFM1='Open lfm file to check...';
  ttOpenDialogLFM2='Open lfm file to check against XML file...';
  ttOpenDialogXML='Open XML file to check...';
  ttSaveDialog='Save results as CSV file...';
  capSaveCSV='&Save as CSV...';
  rsNix='No Session Properties found at all. Listed objects instead.';
  rsVerwaist='X';
  rsKeine='OK. No orphaned items found.';
  rsSavedAs='Saved as ';
  rsCorrected='corrected and saved';
  rsExtFilter='Lazarus-Forms|*.lfm;*.dfm|XML files|*.xml|Text files|*.txt|All files|*.*';
  rsXML='XMLcheck';

  capText='Text viewer';
  capSaveText='Save &text';
  hntSaveText='Save this text to a file';
  ttSaveText='Save text as...';
  hntSynEdit='Show currently opened file'+lineending+'Please change and save this file only if you are sure what you have done!';

  errEmpty='Empty file';
  errNoObj='No objects found';
  errNoXML='XML file not valid or empty';

{header}
 rsHeader='Object;SessionProperty;Orphaned';
 rsObjHeader='Object;Type;Sequ No';
 rsXMLHeader='Object;Value;Unused';

