resourcestring                                     {deutsch}

  rsProgName='SessionPropertyTool';
  capWaisen='&Verwaiste Einträge';
  hntWaisen='Suche verwaiste Einträge in den Session Properties.';
  capXMLcheck='&Prüfe XML';
  hntXMLcheck='Suche ungenutzte Einträge in XML Settings.';
  capClose='&Beenden';
  hntClose='Programm schliessen. Es wird nichts gespeichert.';
  capFilter='Nur verwaiste Einträge';
  hntFilter='Nur verwaiste Einträge anzeigen.';
  capDelete='Lösche unnütze Einträge';
  hntDelete='Lösche unbenutzte Werte in der XML Datei.';
  capFunc='&Funktionen';
  hntStatus='Zähler und Statusmeldungen';
  hntStatusW='Anzahl gelesene Zeilen / Anzahl überprüfter Objekte / Anz. verwaist / Statusmeldungen';
  hntStatusO='Anzahl gelesene Zeilen / Anzahl Objects / leer / Statusmeldungen';

  ttOpenDialogLFM1='lfm Datei zur Suche öffnen...';
  ttOpenDialogLFM2='lfm Datei zum Prüfen gegen XML Datei öffnen...';
  ttOpenDialogXML='XML Datei zum Prüfen öffnen...';
  ttSaveDialog='Ergebnisse als CSV Datei speichern...';
  capSaveCSV='&Als CSV speichern...';
  rsNix='Keine Session Properties gefunden. Dafür Objects angezeigt.';
  rsVerwaist='X';
  rsKeine='OK. Keine verwaisten Einträge';
  rsSavedAs='Gespeichert als ';
  rsCorrected='korrigiert und gespeichert';
  rsExtFilter='Lazarus-Formulare|*.lfm;*.dfm|XML-Dateien|*.xml|Textdateien|*.txt|Alle Dateien|*.*';
  rsXML='XMLcheck';

  capText='Textanzeige';
  capSavetext='&Text speichern';
  hntSaveText='Angezeigten Text in eine Datei speichern.';
  ttSaveText='Text speichern als...';
  hntSynEdit='Anzeige der geöffneten Datei'+lineending+'Bitte nur ändern und speichern, wenn man sicher weiß was man tut!';

  errEmpty='Leere Datei';
  errNoObj='Keine Objects gefunden';
  errNoXML='XML Datei ungültig oder leer';

{header}
 rsHeader='Object;SessionProperty;Verwaist';
 rsObjHeader='Object;Type;Nr';
 rsXMLHeader='Object;Wert;Unnütz';

